// components/Comment.vue
<template>
  <div ref="comment"></div>
</template>

<script setup lang="ts">
const comment = useTemplateRef("comment");

const utterancesSelector = "iframe.utterances-frame";
// ligth, dark, github-light, github-dark, dark_dimmed
const theme = "dark_dimmed";

onMounted(() => {
  const utterancesEl = comment.value.querySelector(utterancesSelector);
  const createUtterancesEl = () => {
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.setAttribute("data-repo", "arch-spatula/arch-spatula.github.io");
    script.setAttribute("data-repo-id", "R_kgDOImK9Dg");
    script.setAttribute("data-category", "General");
    script.setAttribute("data-category-id", "DIC_kwDOImK9Ds4CUzIZ");
    script.setAttribute("data-mapping", "pathname");
    script.setAttribute("data-strict", "0");
    script.setAttribute("data-reactions-enabled", "1");
    script.setAttribute("data-emit-metadata", "0");
    script.setAttribute("data-input-position", "bottom");
    script.setAttribute("data-lang", "ko");
    script.setAttribute("crossorigin", "anonymous");
    script.setAttribute("data-theme", theme);
    script.setAttribute("data-loading", "lazy");

    script.async = true;
    comment.value.appendChild(script);
  };

  const postThemeMessage = () => {
    const message = {
      type: "set-theme",
      theme: theme,
    };
    utterancesEl.contentWindow.postMessage(message, "https://utteranc.es");
  };

  utterancesEl ? postThemeMessage() : createUtterancesEl();
});
</script>

// src/components/Comment/Index.tsx
import React, { useEffect, useRef } from 'react';
import { useColorMode } from '@docusaurus/theme-common';

const utterancesSelector = 'iframe.utterances-frame';

/**
 * @see https://younho9.dev/docusaurus-manage-docs-2
 * @see https://docusaurus.io/docs/next/api/themes/configuration#use-color-mode
 * 위 두 자료를 결합해서 블로그의 다크모드를 구현했습니다.
 */

function Comment() {
  const containerRef = useRef(null);
  const { colorMode } = useColorMode();
  const utterancesTheme = colorMode ? 'dark' : 'light';

  useEffect(() => {
    const utterancesEl = containerRef.current.querySelector(utterancesSelector);

    const createUtterancesEl = () => {
      const script = document.createElement('script');
      script.src = 'https://giscus.app/client.js';
      script.setAttribute('data-repo', 'arch-spatula/arch-spatula.github.io');
      script.setAttribute('data-repo-id', 'R_kgDOImK9Dg');
      script.setAttribute('data-category', 'General');
      script.setAttribute('data-category-id', 'DIC_kwDOImK9Ds4CUzIZ');
      script.setAttribute('data-mapping', 'pathname');
      script.setAttribute('data-strict', '0');
      script.setAttribute('data-reactions-enabled', '1');
      script.setAttribute('data-emit-metadata', '0');
      script.setAttribute('data-input-position', 'bottom');
      script.setAttribute('data-lang', 'ko');
      script.setAttribute('crossorigin', 'anonymous');
      script.setAttribute('data-theme', utterancesTheme);
      script.setAttribute('data-loading', 'lazy');

      script.async = true;
      containerRef.current.appendChild(script);
    };

    const postThemeMessage = () => {
      const message = {
        type: 'set-theme',
        theme: utterancesTheme,
      };
      utterancesEl.contentWindow.postMessage(message, 'https://utteranc.es');
    };

    utterancesEl ? postThemeMessage() : createUtterancesEl();
  }, [colorMode]);

  return <div ref={containerRef} style={{ marginTop: '3rem' }} />;
}

export default Comment;
